from etl.destinations.csv_destination import CSVDestination
from etl.destinations.biblioteca_neo4j_destination import BibliotecaNeo4jDestination
from etl.destinations.neo4j_destination import Neo4jDestination
